# Generated by Django 5.0.2 on 2024-03-16 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM_API', '0003_alter_user1_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='detail',
        ),
        migrations.AddField(
            model_name='user1',
            name='detail',
            field=models.ManyToManyField(null=True, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
